import Navbar from "../components/Navbar";

export const metadata = {
  title: "Nails-project",
  description: "Generated by Next.js",
  keywords: "servicios, diseños, online",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
